# Generated by Django 4.2.4 on 2023-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('modelo_de_negocio', models.CharField(max_length=255)),
                ('tipo_de_cliente', models.CharField(max_length=255)),
                ('outbound', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produto_codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('produto_nome', models.CharField(max_length=255)),
                ('produto_tipo', models.CharField(max_length=255)),
                ('produto_grupo', models.CharField(max_length=255)),
                ('produto_torre', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('transportadora_codigo_sap', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transportadora_nome_sap', models.CharField(max_length=255)),
                ('transportadora_cnpj', models.CharField(max_length=255)),
                ('transportadora_grupo_atlas', models.CharField(max_length=255)),
            ],
        ),
    ]
