# Generated by Django 4.2.4 on 2023-08-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='"sc_sap"."tb_clientes"',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='"sc_sap"."tb_produtos"',
        ),
        migrations.AlterModelTable(
            name='transportadora',
            table='"sc_sap"."tb_transportadoras"',
        ),
    ]
