# Generated by Django 4.2.4 on 2023-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('placa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=255)),
            ],
        ),
    ]
