# Generated by Django 4.2.4 on 2023-08-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minalba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='placa',
            table='"sc_placa"."tb_placas"',
        ),
    ]
